POST http://localhost:8000/api/hasil-ompreng
Accept: application/json
Content-Type: application/json


{
  "data": [
    {
      "nomor_dapur": "D125",
      "tanggal_update": "2025-07-10",
      "line1": 7,
      "line2": 8,
      "line3": 5,
      "line4": 5,
      "line5": 5,
      "line6": 5
    },
    {
      "nomor_dapur": "D126",
      "tanggal_update": "2025-07-14",
      "line1": 15,
      "line2": 15,
      "line3": 10,
      "line4": 10,
      "line5": 10,
      "line6": 10
    }
  ]
}
